query ($seriesId: Long!) {
    contentMyTicket(seriesId: $seriesId, includeWaitfree: true) {
        ticketOwnCount
        ticketRentalCount
        waitfree {
            chargedComplete
        }
    }
}
