query ($seriesId: Long!) {
    contentHomeOverview(seriesId: $seriesId) {
        content {
            title
            thumbnail
            authors
            waitfreeBlockCount
            freeSlideCount
            serviceProperty {
                viewCount
                ratingCount
                ratingSum
            }
        }
    }
}
