query ($input: SearchKeywordInput!) {
    searchKeyword(searchKeywordInput: $input) {
        list {
            thumbnail
            row1
            row2
            row3 {
                metaList
            }
            scheme
        }
        total
    }
}
