query ($param: StaticLandingRankingParamInput!) {
    staticLandingRankingSection(param: $param, sectionId: "") {
        groups {
            items {
                ... on NormalListViewItem {
                    row1
                    scheme
                }
            }
        }
    }
}
