query ($seriesId: Long!, $first: Int, $last: Int, $sortType: String) {
    contentHomeOverview(seriesId: $seriesId) {
        content {
            title
            thumbnail
            authors
            waitfreeBlockCount
            freeSlideCount
            serviceProperty {
                viewCount
                ratingCount
                ratingSum
            }
        }
    }
    contentHomeProductList(seriesId: $seriesId, first: $first, last: $last, sortType: $sortType) {
        totalCount
        edges {
            node {
                row1 {
                    title
                }
                row2
                row3
                scheme
            }
        }
    }
}
